apiVersion: v1
kind: Namespace
metadata:
  name:  one
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: one
  labels:
    app: simple-pod
spec:
  containers:
  - name: simple-pod
    image: busybox
    command:
      - sleep
      - "3600"
---
